### ISSUE TITLE
Start up issue of watchteleboy

### ISSUE THREAD

**Issue by SoerenBoernsen** [reduzent/watchteleboy#32]
It looks to me that watchteleboy script 2.1 fails with the following response 

```
Failed to restore session
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wt/classes.py", line 202, in __restore_session
    assert self.logged_in()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/watchteleboy", line 102, in <module>
    main()
  File "/usr/bin/watchteleboy", line 47, in main
    wts = wt.WatchTeleboySession(env['session_cache'])
  File "/usr/lib/python3/dist-packages/wt/classes.py", line 45, in __init__
    self.__restore_session()
  File "/usr/lib/python3/dist-packages/wt/classes.py", line 205, in __restore_session
    raise WatchTeleboyError
wt.classes.WatchTeleboyError
```

**Comment by reduzent** [comment]
Thanks for reporting. I encountered this, too. Until this is fixed, you can - as a workaround - delete the session_cache file in the .watchteleboy directory:

`rm ~/.watchteleboy/session_cache`
